language: node_js
node_js:
- lts/*
script: ng test --karma-config karma.conf.js
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_deploy:
- npm run test:int
deploy:
  provider: heroku
  api_key:
    secure: gDJ/dz5hkQI9aYQE3S8UPKmUS4rSCeuak1S4hC4ePr0UndSnGKdQRM4Jz2F4k95glFj00hxE8WVsWPs07ybYDcxTNQ03IFq6TIo+Ly+AVNBrRpvFfaHiAIgsIXFPKra58d46zqi+jK/aCRO+12exnOszpp7faIuu56ZoaMm/jdEXOStd9+1P4SiOz0VmqrbDepAUKEOenYhYhHVJuODVWy1XmcnY3f8Ti2jvni89uBPlyNkCJdX4A7XFzz1ZZa9vD5mCi2uT3f5hP7X1EBj4QNlrxedQX3HGh8tdqul7OGlGczbfPKr54sR2Dacwqsk9Bq1Q4qGiGjCMdkVkbozbB0JHGl4v7+PSaQIFHE3xOT8UGGYG9l01msaMMSLqREtFNeIjYfrXKB3BTyvvwY1mK9jQQrDqwQC+5hM/6Kxh5+MmWh+cWxgI0rNiufVpqLX6trwpa8NykAUyEYqq6GCDqZWs3oTPwVNH0yqqplEjnYuGVAVLN/8fZpk2kML/2qUlxTnWXhhcdnju5LnowDCOzNq22mbby7Mzz2ng+/KdupZG1bnwwPvN24E+my7XedjZciQpwy6WeOIrzipxGqxV4u06ri8fx/GDttYcwo61FhjXINessXodrw9hI/dekWin37DjXh/c7Ee95K4HLIxovh5DX/zC+YAyacFUk1fQ8JU=
  app:
    master: ssdc-website
